name: Stage Kong changes for PRD in a PR

on:
  push:
    branches:
      - main
      - workflow/**
    paths:
      - config/kong/.generated/kong.yaml
      - .github/workflows/stage-kong-for-PRD.yaml

jobs:
  reusable-workflow: 
    uses: deirdre-anderson/KongAir/.github/workflows/stage-kong-for-PRD.yaml@main
    secrets: 
      KONNECT_PAT: ${{ secrets.KONNECT_PAT }}



