name: Stage changes for Kong

on:
  push:
    branches:
      - main
      - workflow/**
    paths-ignore:
      - 'PRD/**'
      - 'platform/kong/.generated/kong.yaml'

jobs:

  has-changes:
    name: Have specs, configurations, or pipeline files changed
    runs-on: ubuntu-latest

    outputs:
      are-changes: ${{ steps.changed-files.outputs.files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changed-files
        with:
          filters: |
            files:
              - '.github/workflows/stage-changes-for-kong.yaml'
              - 'flight-data/flights/openapi.yaml'
              - 'flight-data/flights/kong/**'
              - 'flight-data/routes/openapi.yaml'
              - 'flight-data/routes/kong/**'
  reusable-workflow: 
    uses: deirdre-anderson/KongAir/.github/workflows/shared-stage-changes-for-team.yaml@main